version: "3"

services:
  app:
    build: .
    ports:
      - "3000:80"
    depends_on:
      - database
      - elasticsearch
  database:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
  elasticsearch:
    ports:
      - "9200:9200"
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      discovery.type: single-node

volumes:
  mysql:
